"""Adding provider asset market table.

Revision ID: 0363c25292b7
Revises: 01b93e270546
Create Date: 2025-07-20 15:12:55.241449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0363c25292b7"
down_revision: Union[str, Sequence[str], None] = "01b93e270546"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_asset_market",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            comment="The timestamp of the provider asset market",
        ),
        sa.Column(
            "provider_id",
            sa.Integer(),
            nullable=False,
            comment="The identifier of the provider",
        ),
        sa.Column(
            "from_asset_id",
            sa.Integer(),
            nullable=False,
            comment="The identifier of the from asset. This is also called the base asset.",
        ),
        sa.Column(
            "to_asset_id",
            sa.Integer(),
            nullable=False,
            comment="The identifier of the to asset. This is also called the quote asset.",
        ),
        sa.Column(
            "close",
            sa.Float(),
            nullable=True,
            comment="The closing price of the provider asset market",
        ),
        sa.Column(
            "open",
            sa.Float(),
            nullable=True,
            comment="The opening price of the provider asset market",
        ),
        sa.Column(
            "high",
            sa.Float(),
            nullable=True,
            comment="The highest price of the provider asset market",
        ),
        sa.Column(
            "low",
            sa.Float(),
            nullable=True,
            comment="The lowest price of the provider asset market",
        ),
        sa.Column(
            "volume",
            sa.Float(),
            nullable=True,
            comment="The volume traded of the provider asset market",
        ),
        sa.Column(
            "best_bid",
            sa.Float(),
            nullable=True,
            comment="The best bid price of the provider asset market",
        ),
        sa.Column(
            "best_ask",
            sa.Float(),
            nullable=True,
            comment="The best ask price of the provider asset market",
        ),
        sa.ForeignKeyConstraint(
            ["from_asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_asset_id"],
            ["asset.id"],
        ),
        sa.PrimaryKeyConstraint(
            "timestamp",
            "provider_id",
            "from_asset_id",
            "to_asset_id",
            name=op.f("provider_asset_market_pkey"),
        ),
        comment="The provider asset market, will store market data for an asset from a provider.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provider_asset_market")
    # ### end Alembic commands ###
