"""Adding tables for transaction data.

Revision ID: 0ae3917aff7f
Revises: 4e3486fc8e3b
Create Date: 2025-12-19 10:44:17.127364

"""

from typing import Union, Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ae3917aff7f"
down_revision: Union[str, Sequence[str], None] = "4e3486fc8e3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="The unique identifier of the portfolio",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="The name of the portfolio",
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="The description of the portfolio",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the portfolio is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the creation of the portfolio",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the last update of the portfolio",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("portfolio_pkey")),
        comment="The portfolio, represents a collection of assets and their transactions for tracking investment strategies and performance.",
    )
    op.create_table(
        "transaction_group",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="The unique identifier of the transaction group",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp when this group was created",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transaction_group_pkey")),
        comment="Groups related transactions together for market neutral and paired trading strategies. Used to link offsetting long and short positions.",
    )
    op.create_table(
        "transaction_type",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="The unique identifier of the transaction type",
        ),
        sa.Column(
            "symbol",
            sa.String(length=100),
            nullable=False,
            comment="The symbol of the transaction type, e.g. BUY, SELL, TRANSFER, SHORT, COVER, etc.",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="The name of the transaction type, e.g. Buy, Sell, Transfer, Short, Cover, etc.",
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="The description of the transaction type",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the transaction type is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the creation of the transaction type",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the last update of the transaction type",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transaction_type_pkey")),
        sa.UniqueConstraint("symbol"),
        comment="The type of transaction, e.g. buy, sell, transfer, short, cover, etc.",
    )
    op.create_table(
        "portfolio_transaction",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="The unique identifier of the transaction",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            comment="The date and time when the transaction occurred",
        ),
        sa.Column(
            "transaction_type_id",
            sa.Integer(),
            nullable=False,
            comment="The identifier of the transaction type",
        ),
        sa.Column(
            "portfolio_id",
            sa.Integer(),
            nullable=False,
            comment="The identifier of the portfolio this transaction belongs to",
        ),
        sa.Column(
            "from_asset_id",
            sa.Integer(),
            nullable=True,
            comment="The identifier of the source asset in the transaction (e.g., cash for buys, the asset being sold for sells)",
        ),
        sa.Column(
            "to_asset_id",
            sa.Integer(),
            nullable=True,
            comment="The identifier of the destination asset in the transaction (e.g., the asset being bought for buys, cash for sells)",
        ),
        sa.Column(
            "quantity",
            sa.Float(),
            nullable=False,
            comment="The number of units/shares in the transaction",
        ),
        sa.Column(
            "price",
            sa.Float(),
            nullable=False,
            comment="The price per unit at which the transaction occurred",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the creation of the transaction",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the last update of the transaction",
        ),
        sa.ForeignKeyConstraint(
            ["from_asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_type_id"],
            ["transaction_type.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("portfolio_transaction_pkey")),
        comment="Represents individual portfolio transactions including buys, sells, and transfers. Used to track all asset movements within and between portfolios.",
    )
    op.create_table(
        "transaction_group_member",
        sa.Column(
            "transaction_group_id",
            sa.Integer(),
            nullable=False,
            comment="The identifier of the transaction group",
        ),
        sa.Column(
            "portfolio_transaction_id",
            sa.Integer(),
            nullable=False,
            comment="The identifier of the portfolio transaction",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the creation of the transaction group member",
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_transaction_id"],
            ["portfolio_transaction.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_group_id"],
            ["transaction_group.id"],
        ),
        sa.PrimaryKeyConstraint(
            "transaction_group_id",
            "portfolio_transaction_id",
            name=op.f("transaction_group_member_pkey"),
        ),
        comment="Junction table linking transactions to their groups. Enables many-to-many relationship between transactions and groups.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_group_member")
    op.drop_table("portfolio_transaction")
    op.drop_table("transaction_type")
    op.drop_table("transaction_group")
    op.drop_table("portfolio")
    # ### end Alembic commands ###
