"""Changing key columns for provider asset market.

Revision ID: 0be98fdd4b99
Revises: 01b93e270546
Create Date: 2025-07-20 14:58:30.411532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be98fdd4b99'
down_revision: Union[str, Sequence[str], None] = '01b93e270546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_asset_market', sa.Column('from_asset_id', sa.Integer(), nullable=False, comment='The identifier of the from asset. This is also called the base asset.'))
    op.add_column('provider_asset_market', sa.Column('to_asset_id', sa.Integer(), nullable=False, comment='The identifier of the to asset. This is also called the quote asset.'))
    op.drop_constraint(op.f('provider_asset_market_asset_id_fkey'), 'provider_asset_market', type_='foreignkey')
    op.create_foreign_key(None, 'provider_asset_market', 'asset', ['from_asset_id'], ['id'])
    op.create_foreign_key(None, 'provider_asset_market', 'asset', ['to_asset_id'], ['id'])
    op.drop_column('provider_asset_market', 'asset_id')
    op.drop_constraint(op.f('provider_asset_market_pkey'), 'provider_asset_market', type_='primary')
    op.create_primary_key('provider_asset_market_pkey', 'provider_asset_market', ['timestamp', 'provider_id', 'from_asset_id', 'to_asset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_asset_market', sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='The identifier of the asset'))
    op.drop_constraint(op.f('provider_asset_market_from_asset_id_fkey'), 'provider_asset_market', type_='foreignkey')
    op.drop_constraint(op.f('provider_asset_market_to_asset_id_fkey'), 'provider_asset_market', type_='foreignkey')
    op.drop_constraint(op.f('provider_asset_market_pkey'), 'provider_asset_market', type_='primary')
    op.create_foreign_key(op.f('provider_asset_market_asset_id_fkey'), 'provider_asset_market', 'asset', ['asset_id'], ['id'])
    op.drop_column('provider_asset_market', 'to_asset_id')
    op.drop_column('provider_asset_market', 'from_asset_id')
    op.create_primary_key('provider_asset_market_pkey', 'provider_asset_market', ['timestamp', 'provider_id', 'asset_id'])
    # ### end Alembic commands ###
