"""Removing name,description from ProviderAssetGroup and re-naming ProviderAssetGroupAttribute column(s).

Revision ID: 4e3486fc8e3b
Revises: bca303faca0a
Create Date: 2025-10-25 09:38:52.338353

"""

from typing import Union, Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e3486fc8e3b"
down_revision: Union[str, Sequence[str], None] = "bca303faca0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_asset_group", "name")
    op.drop_column("provider_asset_group", "description")
    op.add_column(
        "provider_asset_group_attribute",
        sa.Column(
            "ou_mu",
            sa.Float(),
            nullable=True,
            comment="The mu parameter (speed of mean reversion) for the Ornstein-Uhlenbeck process: dX(t) = μ(θ - X(t))dt + σdW(t)",
        ),
    )
    op.add_column(
        "provider_asset_group_attribute",
        sa.Column(
            "ou_theta",
            sa.Float(),
            nullable=True,
            comment="The theta parameter (long-term mean) for the Ornstein-Uhlenbeck process: dX(t) = μ(θ - X(t))dt + σdW(t)",
        ),
    )
    op.add_column(
        "provider_asset_group_attribute",
        sa.Column(
            "ou_sigma",
            sa.Float(),
            nullable=True,
            comment="The sigma parameter (volatility) for the Ornstein-Uhlenbeck process: dX(t) = μ(θ - X(t))dt + σdW(t)",
        ),
    )
    op.drop_column("provider_asset_group_attribute", "ol_sigma")
    op.drop_column("provider_asset_group_attribute", "ol_mu")
    op.drop_column("provider_asset_group_attribute", "ol_theta")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider_asset_group_attribute",
        sa.Column(
            "ol_theta",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="The theta parameter (long-term mean) for the Ornstein-Uhlenbeck process: dX(t) = μ(θ - X(t))dt + σdW(t)",
        ),
    )
    op.add_column(
        "provider_asset_group_attribute",
        sa.Column(
            "ol_mu",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="The mu parameter (speed of mean reversion) for the Ornstein-Uhlenbeck process: dX(t) = μ(θ - X(t))dt + σdW(t)",
        ),
    )
    op.add_column(
        "provider_asset_group_attribute",
        sa.Column(
            "ol_sigma",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="The sigma parameter (volatility) for the Ornstein-Uhlenbeck process: dX(t) = μ(θ - X(t))dt + σdW(t)",
        ),
    )
    op.drop_column("provider_asset_group_attribute", "ou_sigma")
    op.drop_column("provider_asset_group_attribute", "ou_theta")
    op.drop_column("provider_asset_group_attribute", "ou_mu")
    op.add_column(
        "provider_asset_group",
        sa.Column(
            "description",
            sa.VARCHAR(length=1000),
            autoincrement=False,
            nullable=True,
            comment="The description of the asset group",
        ),
    )
    op.add_column(
        "provider_asset_group",
        sa.Column(
            "name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="The name of the asset group",
        ),
    )
    # ### end Alembic commands ###
