"""Changing column(s) in tables. Adding symbol columns and underlying column(s).

Revision ID: 5caaba3e0458
Revises: 49fa1eedaaa3
Create Date: 2025-06-24 21:48:54.671456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5caaba3e0458"
down_revision: Union[str, Sequence[str], None] = "49fa1eedaaa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset", sa.Column("symbol", sa.String(length=100), nullable=True))
    op.add_column(
        "asset", sa.Column("underlying_asset_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "asset",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "asset", "asset", ["underlying_asset_id"], ["id"])
    op.alter_column(
        "asset_type",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "asset_type",
        "description",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    op.alter_column(
        "content_type",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.add_column("provider", sa.Column("symbol", sa.String(length=100), nullable=True))
    op.add_column(
        "provider", sa.Column("underlying_provider_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "provider",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "provider", "provider", ["underlying_provider_id"], ["id"]
    )
    op.alter_column(
        "provider_asset",
        "asset_code",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.add_column(
        "provider_content",
        sa.Column(
            "provider_external_code",
            sa.String(length=1000),
            nullable=False,
            comment="This is the external identifier for the content and will depend on the content provider and the type of content. For example, for a news article, it could be the URL of the article and for a social media post, it could be the post ID.",
        ),
    )
    op.add_column(
        "provider_content",
        sa.Column(
            "description",
            sa.String(length=5000),
            nullable=True,
            comment="A short description of the content",
        ),
    )
    op.alter_column(
        "provider_content",
        "authors",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    op.alter_column(
        "provider_content",
        "title",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    op.drop_column("provider_content", "provider_unique_identifier")
    op.alter_column(
        "provider_type",
        "name",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "provider_type",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.add_column(
        "provider_content",
        sa.Column(
            "provider_unique_identifier",
            sa.VARCHAR(length=1000),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "provider_content",
        "title",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "provider_content",
        "authors",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_column("provider_content", "description")
    op.drop_column("provider_content", "provider_external_code")
    op.alter_column(
        "provider_asset",
        "asset_code",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_constraint(None, "provider", type_="foreignkey")
    op.alter_column(
        "provider",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_column("provider", "underlying_provider_id")
    op.drop_column("provider", "symbol")
    op.alter_column(
        "content_type",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "asset_type",
        "description",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "asset_type",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_constraint(None, "asset", type_="foreignkey")
    op.alter_column(
        "asset",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_column("asset", "underlying_asset_id")
    op.drop_column("asset", "symbol")
    # ### end Alembic commands ###
