"""Adding asset group table.

Revision ID: bca303faca0a
Revises: 244d1250fc54
Create Date: 2025-09-20 14:49:12.958245

"""

from typing import Union, Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bca303faca0a"
down_revision: Union[str, Sequence[str], None] = "244d1250fc54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_group_type",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
            comment="The unique identifier of the asset group type",
        ),
        sa.Column(
            "symbol",
            sa.String(length=100),
            nullable=False,
            comment="The symbol of the asset group type, e.g. PAIRS_TRADING, CLASSICAL_ARBITRAGE, TRIANGULAR_ARBITRAGE, etc.",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=True,
            comment="The name of the asset group type, e.g. Pairs Trading, Classical Arbitrage, Triangular Arbitrage, etc.",
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="The description of the asset group type, e.g. statistical pairs trading, classical arbitrage, triangular arbitrage, etc.",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the asset group type is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the creation of the asset group type",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The timestamp of the last update of the asset group type",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("asset_group_type_pkey")),
        sa.UniqueConstraint("symbol"),
        comment="The type of asset group, e.g. statistical pairs trading, classical arbitrage, triangular arbitrage, etc.",
    )
    op.add_column(
        "provider_asset_group",
        sa.Column(
            "asset_group_type_id",
            sa.Integer(),
            nullable=False,
            comment="The identifier of the asset group type",
        ),
    )
    op.create_foreign_key(
        None,
        "provider_asset_group",
        "asset_group_type",
        ["asset_group_type_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "provider_asset_group", type_="foreignkey")
    op.drop_column("provider_asset_group", "asset_group_type_id")
    op.drop_table("asset_group_type")
    # ### end Alembic commands ###
