# Basic CI setup: Lint with ruff, run tests with pytest
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Ruff lint
        run: uv run ruff check .
      - name: Ruff format
        run: uv run ruff format --diff .

  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: "Verify Docker is available"
        run: |
          docker --version
          docker info
          echo "Docker is ready for testing"
      
      - uses: astral-sh/setup-uv@v3

      - name: "Install dependencies"
        run: uv sync --group test

      - name: "Test with pytest"
        run: uv run pytest
